env:
    DOCKER_COMPOSE_VERSION: 1.8.0
sudo: false
language: node_js
before_script:
    - sudo apt-get update
    - npm update -g npm
    - docker-compose --version
    - docker ps
    - npm run dev:docker
node_js:
    - node
install:
    - npm ci
script:
    - npm run lint
    - npm run coveralls
services:
    - docker
    - mongodb
    - redis-server
