sudo: true
env:
    - DOCKER_COMPOSE_VERSION=1.8

language: node_js
before_script:
    - sudo apt-get update
    - sleep 15
    - mongo auth --eval 'db.createUser({user:"admin",pwd:"secret",roles:["readWrite"]});'
node_js:
    - node
install:
    - npm ci
script:
    - npm run lint
    - npm run coveralls
services:
    - docker
    - mongodb
    - redis-server
