version: '3.7'

services:
    db:
        image: mongo
        container_name: mongo
        build: ./data
        ports:
            - '27018:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
            MONGO_INITDB_DATABASE: auth
            MONGO_PASSWORD: secret
            MONGO_USERNAME: admin
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - data/db
    cache:
        image: redis:alpine
        container_name: redis
        ports:
            - 6379:6379
        command: ['--requirepass "secret"']
